apiVersion: certManager.k8s.io/v1apha1
kind: CluserIssuer
metadata: 
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'cppragada0509@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
